Tree List component
patternfly/patternfly-ng pull request #120
Opened 2017-08-26 08:29 UTC by dlabrecq

Adding the tree list component. This component makes use of angular-tree-component to provide a tree hierarchy along with drag and drop support, lazy loading of child nodes, etc.

https://github.com/500tech/angular-tree-component

Note that this is a somewhat different component than the original version created for ngx-widgets. For example, it's now one component instead of two, which simplifies things for the end user.

The ngx-widgets component is also based on v2.7.0 of angular-tree-component and Angular 2. This new tree list component uses the latest v4.1.0 of angular-tree-component, which is based on Angular 4. The latest angular-tree-component also uses a different HTML template layout, so some porting/customizing was necessary.

This new tree list component closely mimics the existing patternfly-ng list component, which uses the latest pf-list layout from PatternfFly core. Both list and tree list components are able to share many of the same features such as checkbox selection, single row (click) selection, multiple row selection, etc. These features are not available with the ngx-widgets component.

Since the list and tree list components have so much in common, I've refactored the existing list component a bit and moved common functionality to base classes for the two components to share. Note that the existing list component class names have not changed.

Example:
https://rawgit.com/dlabrecq/patternfly-ng/tree-list-dist/dist-demo/#/tree-list

![screen shot 2017-08-26 at 3 50 40 am](https://user-images.githubusercontent.com/17481322/29739843-04f01d14-8a16-11e7-979b-dbfae797cdb2.png)

2017-08-26 08:45 UTC, dlabrecq commented
FYI, @catrobson

2017-08-28 17:08 UTC, mindreeper2420 commented
LGTM from CSS/HTML design end.

2017-08-28 17:08 UTC, AdamJ approved these changes

2017-08-28 18:30 UTC, dgutride requested changes

2017-08-28 18:30 UTC, dgutride commented on src/app/list/basic-list/examples/list-compound-example.component.html
> +        <include-content src="src/app/list/list/examples/list-compound-example.component.html"></include-content>
Should this be basic-list, too?

2017-08-28 18:30 UTC, dgutride commented on src/app/list/basic-list/examples/list-heading-example.component.html
> +        <include-content src="src/app/list/list/examples/list-heading-example.component.html"></include-content>
basic-list...

2017-08-28 18:34 UTC, dlabrecq commented on src/app/list/basic-list/examples/list-compound-example.component.html
> +        <include-content src="src/app/list/list/examples/list-compound-example.component.html"></include-content>
Yes. Thanks!

2017-08-28 18:35 UTC, dlabrecq commented
Reviewed the demo with Adam and fixed the HTML includes Dana pointed out. Should be good to go now.

2017-08-28 18:45 UTC, dgutride approved these changes

2017-08-28 18:45 UTC, merged