Add LESS linter
patternfly/patternfly-ng pull request #139
Opened 2017-09-29 19:24 UTC by agathver

Adds [gulp-lesshint](https://www.npmjs.com/package/gulp-lesshint) to the gulp build process.

I have not specified any style configuration, so the default configuration generates a handful of warnings now.

Closes #84

2017-10-05 15:34 UTC, dlabrecq requested changes
This generates a ton of warnings.

![screen shot 2017-10-05 at 11 26 08 am](https://user-images.githubusercontent.com/17481322/31235940-b696c8fa-a9c0-11e7-8508-106e129295db.png)

I think we really need a style configuration file before we can close #84?

OSIO uses stylelint and stylelint-webpack-plugin. I believe we closely follow their style config, so perhaps their stylelintrc file would help here?

2017-10-06 06:19 UTC, agathver commented
@dlabrecq Should we use [gulp-stylelint](https://github.com/olegskl/gulp-stylelint) instead ? In that case we can just reuse the style configuration of OSIO ?

2017-10-06 13:09 UTC, dlabrecq commented
Eventually, we will also duplicate OSIO's TS and HTML linters, so it may be best to add them all to webpack?

I was thinking we would duplicate what OSIO has done in webpack.common.config? Then, copy ..stylelintignore and .stylelintrc to this repo.

      const StyleLintPlugin = require('stylelint-webpack-plugin');
      ...
      /*
       * StyleLintPlugin
       */
      new StyleLintPlugin({
        configFile: '.stylelintrc',
        syntax: 'less',
        context: 'src',
        files: '**/*.less',
        failOnError: true,
        quiet: false,
      })

2017-10-06 18:39 UTC, agathver commented
@dgutride By the look of our gulpfile, it seems we are processing less into css before in enters webpack. Or, am I mistaken ?

2017-10-09 13:22 UTC, dlabrecq commented
You're correct, we're processing the less before webpack in order to in-line the CSS. This is necessary to support AOT compilation. We could probably move that via webpack, but not something we must tackle now.

If you can use gulp-stylelint with OSIO's style config, let's do that instead?

2017-10-22 03:25 UTC, closed without merging