Save filter feature
patternfly/patternfly-ng pull request #155
Opened 2017-10-15 03:35 UTC by dlabrecq

Add functionality to support save filter feature from https://github.com/fabric8-ui/fabric8-ux/issues/664

Example: Click on "Save" tab
https://rawgit.com/dlabrecq/patternfly-ng/save-filter-dist/dist-demo/#/filters

![screen shot 2017-10-14 at 11 29 06 pm](https://user-images.githubusercontent.com/17481322/31581362-dce647d2-b137-11e7-9e1e-6c389333f6a5.png)

![screen shot 2017-10-14 at 11 29 51 pm](https://user-images.githubusercontent.com/17481322/31581363-e08ccd5c-b137-11e7-998a-ec4699d8b911.png)

https://gfycat.com/gifs/detail/UnluckyUnrulyDuckbillcat

2017-10-15 16:30 UTC, dlabrecq commented
FYI, @catrobson

2017-10-19 16:56 UTC, dgutride submitted a review, later dismissed

2017-10-19 17:33 UTC, catrobson commented
@dlabrecq is there any way to do more of a confirmation on the deletion of a filter?  Not sure if that gets too complex for the pattern.  It seems pretty easy to accidentally delete a filter without a "are you sure" step. 

Also, can we add a label "Name your filter" on the field in the save dropdown? 
![image](https://user-images.githubusercontent.com/3739227/31785101-18788c90-b4d2-11e7-820a-82266cbbd1c6.png)

2017-10-19 19:15 UTC, dlabrecq commented
Regarding the delete filter, we probably could add something. However, the user can also delete all filters by clicking on the "clear all" link. We don't have a confirmation there, either.

A label is easy. Or, we can do place holder text?

2017-10-20 15:50 UTC, dlabrecq commented
@catrobson I added a label to the save filter input. Please let me know if you want the label on top, instead?

![screen shot 2017-10-20 at 10 11 07 am](https://user-images.githubusercontent.com/17481322/31829924-b81caf46-b58c-11e7-8ea1-c6afb7ef0f3c.png)

2017-10-20 16:08 UTC, dlabrecq commented
@catrobson I wasn't able to add a confirmation popover to the remove filter button. The menu items are already wrapped in an anchor, which prevents the Angular Bootstrap popover from displaying. The remove filter icon is located within the anchor in order for the hover state to display properly.

If there is a different design you would like to consider, please let me know?

2017-10-20 17:25 UTC, dlabrecq commented
Instead of a confirmation popover, I was able to change the remove filter icon and tooltip when selected. This forces the user to confirm by clicking the new icon. We can use a different icon, but please let me know if something like this will work?

If the user selects a different filter to remove or another filter to apply, the original icon is restored.

Remove filter:
![screen shot 2017-10-20 at 1 19 33 pm](https://user-images.githubusercontent.com/17481322/31833877-f0dc7430-b599-11e7-9205-7497ab3bb714.png)

Confirm remove filter:
![screen shot 2017-10-20 at 1 20 02 pm](https://user-images.githubusercontent.com/17481322/31833898-05b4de9c-b59a-11e7-8124-f4fd33016173.png)

2017-10-20 18:40 UTC, catrobson commented
Label on top for the filter naming would be better.  The validation check to remove a filter doesn't follow typical standards, but presents some interesting alternatives.  How you have it with a tooltip doesn't feel quite right to me, let me try out one or two things as alternatives and post them back here.

2017-10-28 09:58 UTC, dlabrecq commented
Added Brian's slide-in design for the delete filter confirmation. May need some minor tweaks?

Example: Click on "Save" tab
https://rawgit.com/dlabrecq/patternfly-ng/save-filter-dist/dist-demo/#/filters

Trash can:
![screen shot 2017-10-28 at 5 55 00 am](https://user-images.githubusercontent.com/17481322/32133386-d1085bf4-bba4-11e7-8132-8c422eee187b.png)

Slide-in:
![screen shot 2017-10-28 at 5 54 41 am](https://user-images.githubusercontent.com/17481322/32133387-d8da655c-bba4-11e7-9da9-ab4c57e9ea19.png)

Save Filter Label:
![screen shot 2017-10-28 at 5 55 29 am](https://user-images.githubusercontent.com/17481322/32133391-e222a84a-bba4-11e7-95a4-79dbbe20f687.png)

2017-10-30 13:31 UTC, mindreeper2420 commented
Clicking on the trash can and then having to move my mouse to the left to click the checkmark feels weird. Would it be possible to swap the checkmark and 'X', so that the user does not have to move their mouse?

2017-10-30 19:54 UTC, dlabrecq commented
Yes, I've swapped the x and the check mark. Brian mentioned the same.

2017-11-02 14:53 UTC, dgutride submitted a review, later dismissed

2017-11-02 15:01 UTC, AdamJ requested changes

2017-11-02 15:01 UTC, mindreeper2420 commented on src/app/filter/examples/filter-save-example.component.html
> +    <div class="col-md-12">
Not sure how this will work, with this being `col-md-` and other pieces being `col-xs-`

2017-11-02 15:01 UTC, mindreeper2420 commented on src/app/filter/filter-fields.component.less
> +    transition-duration: 1s;
I'd move this down to `.5s`, as 1 second feels like it is taking too long.

2017-11-02 15:01 UTC, mindreeper2420 commented on src/app/filter/filter-results.component.less
> +    @media (min-width: 768px) {
use Bootstrap's native media query variable:
```
@media (min-width: @screen-sm-min) { width: 15em; }
```

2017-11-02 15:57 UTC, AdamJ approved these changes

2017-11-02 16:45 UTC, merged