Feature pf notification drawer
patternfly/patternfly-ng pull request #334
Opened 2018-04-17 20:11 UTC by akoserwal

2018-04-18 07:26 UTC, akoserwal commented
#146

2018-04-24 17:41 UTC, mindreeper2420 commented on src/app/notification/notification-drawer/example/notification-drawer-example.component.html
> +
can you remove this empty line?

2018-04-24 17:41 UTC, mindreeper2420 commented on src/app/notification/notification-drawer/notification-drawer.component.html
> +
empty line here

2018-04-30 07:04 UTC, akoserwal commented
@mindreeper2420 : done

2018-04-30 12:51 UTC, mindreeper2420 commented
@dlabrecq can you review as well? CSS/HTML is good.

2018-04-30 12:52 UTC, AdamJ submitted a review, later dismissed
CSS/HTML approved.

2018-04-30 15:17 UTC, dlabrecq commented
Yes, I plan to review as well. Sorry, been busy with work for summit.

2018-05-02 19:56 UTC, dlabrecq commented
Sorry for the delay, been busy with summit work, but I'm starting to review now. I haven't dove into the code yet, but the example looks nice. Here are a couple quick notes so I don't lose my thought.

1. Can you please add an actions area so we can confirm the notification actions are working as expected?
2. For next time, please setup an example to run via rawgit? Adam and I are able to run the example locally, so not a big deal, but not all designers have that ability.

Instructions below.
https://github.com/patternfly/patternfly-ng/blob/master/CONTRIBUTING.md

2018-05-02 21:03 UTC, dlabrecq requested changes
Looks great! Easy to review. Just minor comments

2018-05-02 21:03 UTC, dlabrecq commented on src/app/notification/notification-drawer/notification-drawer.component.html
> +  <div *ngIf="notificationGroups" pf-fixed-accordion scroll-selector=".panel-body">
How are pf-fixed-accordion and scroll-selector being used here? I don't see any new directives in this PR. In fact, the drawer still appears to render properly if I remove them

2018-05-02 21:03 UTC, dlabrecq commented on src/app/notification/notification-drawer/notification-drawer.component.html
> +  <div *ngIf="!notificationGroups" class="apf-blank-notification-groups">
apf-blank-notification-groups seems to be a non-existing selector?

2018-05-02 21:03 UTC, dlabrecq commented on src/app/notification/notification-drawer/example/notification-drawer-example.component.html
> +  </div>
Seems to be missing an ending div tag

2018-05-02 21:03 UTC, dlabrecq commented on src/app/notification/notification-drawer/example/notification-drawer-example.component.html
> +              <div uib-dropdown class="dropdown pull-right dropdown-kebab-pf" *ngIf="notify.moreActions.length > 0">
It seems only the pull-right selector us needed here? I was able to remove uib-dropdown, dropdown, and dropdown-kebab-pf.

Note that we're not using the old uib-dropdown directive for dropdowns. If you need a dropdown, please use ngx-boostrap.

2018-05-02 21:03 UTC, dlabrecq commented on src/app/notification/notification-drawer/example/notification-drawer-example.component.html
> +                  {{notify.message}}
Do any of the examples show tooltips for you? I see tooltips for the kebab, but not here.

2018-05-02 21:03 UTC, dlabrecq commented on src/app/notification/notification-drawer/notification-drawer.component.html
> +              <pfng-empty-state [config]="emptyStateConfig"></pfng-empty-state>
I see that the empty state config is used in two places. I'm wondering if we should have a unique empty state for each notification and one just for the notification drawer itself? If one isn't provided, perhaps we just apply the one for the notification drawer. Thoughts?

2018-05-02 21:03 UTC, dlabrecq commented on src/app/notification/notification-drawer/notification-drawer.component.ts
> +  hasNotifications(group: NotificaitonGroup[]) {
Please add return types to the methods. For example:

hasNotifications(group: NotificaitonGroup[]): boolean
onClose(): void
...

2018-05-02 21:03 UTC, dlabrecq commented on src/app/notification/notification-group.ts
> +  subHeading: string;
If this isn't required, please add a '?' char

2018-05-03 05:51 UTC, akoserwal commented on src/app/notification/notification-drawer/notification-drawer.component.html
> +  <div *ngIf="notificationGroups" pf-fixed-accordion scroll-selector=".panel-body">
@dlabrecq : I'll remove them.

2018-05-03 07:27 UTC, akoserwal commented on src/app/notification/notification-drawer/notification-drawer.component.html
> +  <div *ngIf="!notificationGroups" class="apf-blank-notification-groups">
@dlabrecq : Sure, I'll remove it

2018-05-03 07:28 UTC, akoserwal commented on src/app/notification/notification-drawer/example/notification-drawer-example.component.html
> +  </div>
@dlabrecq : oh, yes!

2018-05-03 10:35 UTC, akoserwal commented on src/app/notification/notification-drawer/example/notification-drawer-example.component.html
> +  </div>
done

2018-05-03 11:02 UTC, akoserwal commented on src/app/notification/notification-drawer/notification-drawer.component.html
> +              <pfng-empty-state [config]="emptyStateConfig"></pfng-empty-state>
@dlabrecq: For unique empty state, we have empty state config property defined in NotificationGroup and one emptyconfig for the notification drawer.

2018-05-03 15:11 UTC, dlabrecq commented on src/app/notification/notification-drawer/notification-drawer.component.html
> +              <pfng-empty-state [config]="emptyStateConfig"></pfng-empty-state>
That sounds good

2018-05-07 15:10 UTC, akoserwal commented
@dlabrecq : please can you review now.

2018-05-08 11:19 UTC, jeff-phillips-18 commented
The notification drawer should scroll the inner body of the notification groups rather than the entire drawer. That is, similar to the fixed height accordion, all the groups should be visible at all times and the scrolling should occur within the open group.

This is done a couple of different ways. In PF core and in Angular Patternfly, there is javascript used to compute and set the height of the body, listening for window resize events as well to update this height. In the patternfly-react repo flexbox is used to set the heights appropriately.

I see that there is a use of `pf-fixed-accordion` at https://github.com/patternfly/patternfly-ng/pull/334/files#diff-c7e7858ac8154ee94820361e24979b53R17 which appears to be desiring to use the fixed accordion which has not yet been implemented here.

2018-05-08 11:45 UTC, akoserwal commented
@jeff-phillips-18: thanks, I'll work on the scroll part.

2018-05-08 13:27 UTC, dlabrecq commented
Thank you for making the requested changes -- looking good. Could you please update the actions text area when the kebab options are selected?

2018-05-09 09:22 UTC, akoserwal commented
@jeff-phillips-18 : scroll should be visible only for notification tabs which have loading spinner ?

2018-05-09 10:50 UTC, jeff-phillips-18 commented
The scroll should be in the group body whenever there are more notifications than can be included without pushing the following group headers out of view. This functionality can be seen at https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?selectedKind=NotificationDrawer&selectedStory=Notification%20Drawer&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

2018-05-09 12:40 UTC, akoserwal commented
@jeff-phillips-18 : got it, thanks

2018-05-09 19:44 UTC, akoserwal commented
@jeff-phillips-18 : please can you check the flexbox approach picked from patternfly-react.

2018-05-10 07:12 UTC, akoserwal commented
@jeff-phillips-18: thank you for your help. @dlabrecq: please can you review now.

2018-05-10 19:56 UTC, dlabrecq approved these changes
Built and tested locally. Confirmed that the notification drawer now scrolls the inner body of each notification group.

2018-05-10 20:24 UTC, jeff-phillips-18 approved these changes

2018-05-10 22:30 UTC, merged