fix(list): make more areas clickable for expansion and add hover styles
patternfly/patternfly-ng pull request #369
Opened 2018-05-29 20:46 UTC by jschuler

Addresses https://github.com/patternfly/patternfly-ng/issues/317

2018-05-30 17:17 UTC, dlabrecq commented
It appears you have setup Travis successfully, so it would be great to include an example link for other reviewers. 

Your rawgit URL (for this example) is:
https://rawgit.com/jschuler/patternfly-ng/list-item-toggle-expand-dist/dist-demo/#/list

2018-05-30 17:19 UTC, dlabrecq requested changes
I was able to build and test locally. Looks great!

I'm glad you were able to address the actions area. Clicking on the action buttons still works as expected.

Just a couple very small nits

2018-05-30 17:19 UTC, dlabrecq commented on src/app/list/basic-list/list.component.ts
> +  private toggleExpandArea($event: any, item: any): void {
I believe the event type should be `MouseEvent`. We don't want to use type `any` when possible -- `item` is an exception.

2018-05-30 17:19 UTC, dlabrecq commented on src/app/list/basic-list/list.component.ts
> +    if ($event.target !== $event.currentTarget) return;
Please use brackets for the if-statements.

2018-05-30 19:24 UTC, jschuler commented
Thanks @dlabrecq, made those changes

2018-05-31 14:12 UTC, dlabrecq approved these changes
Looks good !

2018-05-31 14:14 UTC, merged