Add readme and contributions guides
patternfly/patternfly-ng pull request #41
Opened 2017-06-28 20:31 UTC by dgutride

These can be viewed more easily here:
https://github.com/dgutride/patternfly-ng/tree/readme

@catrobson

2017-06-28 23:17 UTC, mindreeper2420 commented on CONTRIBUTING.md
> + ``` angular2html
this doesn't appear to be recognized by the prettifyer - can it be changed to just ```html ?

2017-06-28 23:52 UTC, gperdomor approved these changes

2017-06-29 00:46 UTC, catrobson requested changes
Left a few comments and suggestions.

2017-06-29 00:46 UTC, catrobson commented on CONTRIBUTING.md
> + - Documentation:
Are the next bullets meant to be indented, or is this bullet missing information?

2017-06-29 00:46 UTC, catrobson commented on CONTRIBUTING.md
> +## <a name="submit"></a> Submission guidelines
I'm not sure whether this should be part of submission guidelines or another section about Submission review process, but I think we should explain that submissions will be reviewed against PatternFly standards.  The text I've written up about this:

Any Angular-ng patterns submitted for contribution will be reviewed by designers on this repo associated with the PatternFly project to ensure that contributions match the PatternFly design standards for each component.  This design review is used to make sure that it meets one of the following criteria:

- Matches the "gold standard" design specifications as designed by PatternFly
- Matches the design specifications provided for a certain project and has been made general enough to work for other projects
- Goes through a design review and subsequent matching design documentation issues are created for PatternFly to match this contribution

2017-06-29 00:46 UTC, catrobson commented on CONTRIBUTING.md
> +We follow the [Angular style guide](https://angular.io/guide/styleguide) for all Angular code.  Most general questions about how things should be named, where files should be lived and overall file s
"where files should live"

2017-06-29 00:46 UTC, catrobson commented on README.md
> + - Search our [GitHub issues][github-issues]
Not a live link by the looks of it.

2017-06-29 07:06 UTC, dlabrecq approved these changes
LGTM

2017-06-29 12:44 UTC, AdamJ approved these changes

2017-06-29 12:44 UTC, dgutride commented
thanks @catrobson - all changes have been made

2017-06-29 12:46 UTC, gperdomor approved these changes

2017-06-29 19:39 UTC, merged