Changend class name of "NotificaitonGroup" to "NotificationGroup" (#451)
patternfly/patternfly-ng pull request #452
Opened 2018-12-14 10:28 UTC by LarsLuz

2018-12-14 10:32 UTC, patternfly-build commented
Deploy preview for *patternfly-ng* ready!

Built with commit ec2894015ff070fa341bb0a823aa01aad2025929

https://deploy-preview-452--patternfly-ng.netlify.com

2018-12-14 21:02 UTC, dlabrecq requested changes
Not sure why the CI build failed, but have restarted it

2018-12-14 21:02 UTC, dlabrecq commented on src/app/notification/index.ts
> -export { NotificaitonGroup } from './notification-group';
Although trivial, this may be a breaking change? In addition to these modifications, I'm thinking we should add the export below to avoid breaking existing apps.

export { NotificationGroup as NotificaitonGroup } from './notification-group'; // deprecated

2018-12-14 21:45 UTC, joshuawilson commented on src/app/notification/index.ts
> -export { NotificaitonGroup } from './notification-group';
I was wondering if that might break things. I think this is a good way to handle that.

2018-12-17 15:06 UTC, LarsLuz commented on src/app/notification/index.ts
> -export { NotificaitonGroup } from './notification-group';
Would
`export { NotificationGroup as NotificaitonGroup } from './notification-group';`
be sufficient enough?

2018-12-17 16:24 UTC, dlabrecq commented
@LarsLuz It appears that a test is failing.

https://travis-ci.org/patternfly/patternfly-ng/builds/469072033#L1270

2018-12-17 17:01 UTC, LarsLuz commented
It seems like the a test of the donut chart is failing. I do not really understand why, it seems unrelated to the name change of NotifiicationGroup.

The offending test:
https://travis-ci.org/patternfly/patternfly-ng/builds/469072033#L1129

2018-12-17 19:59 UTC, dlabrecq commented
The tests fail locally, but commits 8476209 and ec28940 seem to work.

It appears that the last addition is causing problems. We may not be able to define NotificationGroup as two different things in the same index.ts file?

`export { NotificationGroup as NotificaitonGroup } from './notification-group'`

2018-12-18 08:42 UTC, LarsLuz commented
We could also create a stub class with the old name and let it inherit NotificationGroup?
What do you think?

2018-12-18 16:38 UTC, dlabrecq commented
Sounds good idea to me. I was thinking about using a stub class -- and marking it deprecated.

2018-12-29 05:17 UTC, dlabrecq approved these changes

2018-12-29 05:17 UTC, merged

2019-09-04 15:23 UTC, patternfly-build commented
:tada: This PR is included in version 4.5.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/patternfly-ng)
- [GitHub release](https://github.com/patternfly/patternfly-ng/releases/tag/v4.5.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: